-- Gym backend initial schema
-- Flyway owns database structure. Hibernate does not create or update tables.

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE users (
    id VARCHAR(36) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL,
    locked BOOLEAN NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    last_login_at TIMESTAMP,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE members (
    id VARCHAR(36) PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(255) NOT NULL UNIQUE,
    date_of_birth DATE,
    status VARCHAR(20) NOT NULL,
    join_date DATE NOT NULL,
    user_id VARCHAR(36) UNIQUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_members_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE membership_plans (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    duration_days INTEGER NOT NULL,
    price NUMERIC(19, 2) NOT NULL,
    perks VARCHAR(255)
);

CREATE TABLE memberships (
    id VARCHAR(36) PRIMARY KEY,
    member_id VARCHAR(36) NOT NULL,
    plan_id VARCHAR(36) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_memberships_member FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_memberships_plan FOREIGN KEY (plan_id) REFERENCES membership_plans(id)
);

CREATE TABLE class_sessions (
    id VARCHAR(36) PRIMARY KEY,
    class_name VARCHAR(255) NOT NULL,
    class_description VARCHAR(255),
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    max_capacity INTEGER NOT NULL,
    current_enrollment INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE class_enrollments (
    id VARCHAR(36) PRIMARY KEY,
    member_id VARCHAR(36) NOT NULL,
    class_session_id VARCHAR(36) NOT NULL,
    waitlisted BOOLEAN NOT NULL,
    waitlist_promoted_at TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_enrollments_member FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_enrollments_class FOREIGN KEY (class_session_id) REFERENCES class_sessions(id)
);

CREATE TABLE equipment (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL,
    purchase_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE equipment_maintenance_records (
    id VARCHAR(36) PRIMARY KEY,
    equipment_id VARCHAR(36) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    reported_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    notes VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_maintenance_equipment FOREIGN KEY (equipment_id) REFERENCES equipment(id)
);

CREATE TABLE attendance (
    id VARCHAR(36) PRIMARY KEY,
    member_id VARCHAR(36) NOT NULL,
    class_session_id VARCHAR(36),
    check_in_time TIMESTAMP NOT NULL,
    check_out_time TIMESTAMP,
    duration_minutes INTEGER,
    CONSTRAINT fk_attendance_member FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_attendance_class FOREIGN KEY (class_session_id) REFERENCES class_sessions(id)
);

CREATE INDEX idx_members_status ON members(status);
CREATE INDEX idx_memberships_member ON memberships(member_id);
CREATE INDEX idx_memberships_status ON memberships(status);
CREATE INDEX idx_memberships_end_date ON memberships(end_date);
CREATE INDEX idx_class_sessions_start_time ON class_sessions(start_time);
CREATE INDEX idx_class_sessions_status ON class_sessions(status);
CREATE INDEX idx_class_enrollments_class ON class_enrollments(class_session_id);
CREATE INDEX idx_class_enrollments_member ON class_enrollments(member_id);
CREATE INDEX idx_maintenance_equipment ON equipment_maintenance_records(equipment_id);
CREATE INDEX idx_attendance_member ON attendance(member_id);
CREATE INDEX idx_attendance_check_in_time ON attendance(check_in_time);

INSERT INTO roles (name) VALUES ('ADMIN'), ('TRAINER'), ('MEMBER');
