name: Gym Backend CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SERVER_PORT: ${{ vars.SERVER_PORT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Test
        run: bash mvnw -B clean test

      - name: Package
        run: bash mvnw -B package -DskipTests

      - name: Build Docker image
        run: docker build -t gym-backend:${{ github.sha }} .